### ISSUE TITLE
Show sidebar without active filteres

### ISSUE THREAD

**Issue by workgena** [activeadmin-plugins/active_admin_scoped_collection_actions#3]
Allow users to perform actions with absolutely all records. 
It means show sidebar without active filters or scope.

It should be configurable.

```ruby
config.scoped_collection_actions_always = true
```

**Comment by Fivell** [comment]
would be better just 
```
config.scoped_collection_actions_conditions =  -> { true }
```
if not overrided used default which is
```
config.scoped_collection_actions_conditions = -> {  (params[:q] || params[:scope]) && active_admin_config.scoped_collection_actions.any? }

```

**Comment by workgena** [comment]
Use:

```ruby
config.scoped_collection_actions_if = -> { true }
```

https://github.com/activeadmin-plugins/active_admin_scoped_collection_actions#why-i-dont-see-sidebar-with-collection-actions
