### ISSUE TITLE
How to use this with authorization?

### ISSUE THREAD

**Issue by vfonic** [activeadmin-plugins/active_admin_scoped_collection_actions#38]
Hey!

Just discovered this gem! It does exactly what I need! Thanks!

One thing I'm not sure about is how does this work with an authorization adapter, like Pundit or CanCanCan? (I use Pundit)

Does it call `destroy?` for every `id` or does it call `destroy_all?` or?

Thanks!

**Comment by Fivell** [comment]
@vfonic 
it checks against batch_edit and batch_destroy https://github.com/activeadmin-plugins/active_admin_scoped_collection_actions/blob/090d4e5264192d7a8fdb34e313633af2bfcde679/lib/active_admin_scoped_collection_actions/dsl.rb#L20
