### ISSUE TITLE
support for active_admin_datetimepicker

### ISSUE THREAD

**Issue by Fivell** [activeadmin-plugins/active_admin_scoped_collection_actions#4]
is it possible to support for https://github.com/activeadmin-plugins/active_admin_datetimepicker ?

**Comment by workgena** [comment]
The easiest way is to handle opened event and override default datepicker. Example

```javascript
$(document).ready ->
  $('body').on 'mass_update_modal_dialog:after_open', (e, form) ->
    $(form).find('input[type=datepicker]').removeClass('datepicker').addClass('date-time-picker')
    setupDateTimePicker form
```

**Comment by Fivell** [comment]
@workgena , why replace? What if there are several inputs one with date and another with date time .
I mean maybe it is possible to handle it there https://github.com/workgena/active_admin_scoped_collection_actions/blob/master/vendor/assets/javascripts/lib/dialog_mass_fields_update.js.coffee#L4

**Comment by workgena** [comment]
Close it for now. 
Feel free to open it again, if current solution wouldn't work for you.
