### ISSUE TITLE
Can add labels to the fields?

### ISSUE THREAD

**Issue by pedromacoritto** [activeadmin-plugins/active_admin_scoped_collection_actions#40]
Example:
`name: 'text', label: 'Nombre',`
or
`price: 'integer' as 'Precio',`

or something like that, thanks for the gem!

**Comment by workgena** [comment]
_Unfortunately it **can not be done**._

JavaScript takes name of the field and puts it into `<label>{name}</label>` (makes first letter Capital).

This behaviour is deep in the core of the lib and hard to change.

PS: The obvious solution would be to use i18n, - such PR is welcome. I'm afraid that maintainers would not be doing this change by themselves.
